# Generated by Django 4.1.1 on 2022-12-07 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('time', models.IntegerField()),
                ('work_project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='work.work')),
                ('worker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
