# Generated by Django 4.1.1 on 2022-12-07 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='work_project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='work.work'),
        ),
        migrations.AddField(
            model_name='entry',
            name='worker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to=settings.AUTH_USER_MODEL),
        ),
    ]
